### ISSUE TITLE
Server Error (500) on Github login

### ISSUE THREAD

**Issue by iamthememory** [landscapeio/landscape-issues#175]
When trying to sign up with Github, clicking any of the Login/Sign in with Github links yields a page with only "Server Error (500)" on it after authenticating with Github. This has been consistent for the past day or two, and occurs with both Firefox and Chromium on Linux.

**Comment by carlio** [comment]
@iamthememory Could you try again now? I'm not sure why this is happening to be honest but there seem to be intermittent failures with the queue right now...

**Comment by iamthememory** [comment]
@carlio Still happening on Chromium, Firefox, and Chrome.

**Comment by carlio** [comment]
This hopefully is fixed now, I just moved the whole service. Sorry to be a bother, but could you try again @iamthememory ?

**Comment by iamthememory** [comment]
@carlio Still getting 500s on login with Chromium, Firefox, and Chrome as of now.

**Comment by carlio** [comment]
@iamthememory Ok, I have figured this out now - you should be able to log in. I'm not quite sure why it happened but your user didn't have a user model associated with it.

**Comment by iamthememory** [comment]
@carlio Thanks. I was able to successfully login without any issues now.

**Comment by carlio** [comment]
Hurrah!
