### ISSUE TITLE
Pull Requests don't get the status update

### ISSUE THREAD

**Issue by tomato42** [landscapeio/landscape-issues#202]
I got a pull request for my repo: https://github.com/tomato42/tlslite-ng/pull/68
but I don't see landscape status update for it, but I see it for pull requests I created myself: https://github.com/tomato42/tlslite-ng/pull/67

**Comment by carlio** [comment]
@tomato42 thanks for the report, seems I was setting the status on the "from" repo instead of the "base" repo - should now be fixed for future PRs :+1:

**Comment by tomato42** [comment]
nice, thanks! will report back if it didn't help

**Comment by tomato42** [comment]
After the patches were reworked and pushed again I still don't see the status update for it...
