### ISSUE TITLE
landscape not picking up all repositories

### ISSUE THREAD

**Issue by satra** [landscapeio/landscape-issues#23]
i just synced github with landscape and it is not picking up all the repositories i have access to. in particular i'm interested in nipy/nipype.

**Comment by carlio** [comment]
I checked in on it and it seems to have found the repository, although the check did not work due to a bug, which is now fixed. Can you tell me how long it was between signing up to seeing the repository please? I will look into why it did not appear straight away.

**Comment by satra** [comment]
it still doesn't seem to show up: i'm talking about nipy/nipype not satra/nipype - which is my fork of nipy/nipype.

**Comment by carlio** [comment]
Ah sorry, I misunderstood. 

After looking into it a bit more, this seems to be due to your membership of the organisation 'nipy' not being public. The GitHub API should be returning even 'private' organisation memberships when using your OAuth token but it is not currently, so I'll contact them about it and see if the documentation or the API is incorrect.

In the mean time, if you don't mind making your organisation membership public (you can do that here: https://github.com/nipy?tab=members) then Landscape will (hopefully!) pick up those repositories.

**Comment by carlio** [comment]
I'll update this issue when I get a response from the GitHub guys.

**Comment by satra** [comment]
looks good from my end now. thanks for looking into it.

**Comment by carlio** [comment]
Ok great!
