### ISSUE TITLE
Failure reason: Prospector execution failed

### ISSUE THREAD

**Issue by Omkar20895** [landscapeio/landscape-issues#239]
Hi, I have been trying to deploy landscape into my git repo[0] but I am getting the same error for every check.

![screen shot 2016-07-07 at 3 30 38 pm](https://cloud.githubusercontent.com/assets/11131863/16649710/d7fef2d0-4457-11e6-9287-15e687f6fec2.png)

Please look into this. Thanks. 

[0] https://github.com/lewismc/podaacpy

**Comment by Omkar20895** [comment]
@carlio can you please look into this issue. Thanks. :)

**Comment by flother** [comment]
I'm having the same problem — you can [see the Landscape error output here](https://landscape.io/github/flother/htmltab/4).

Landscape worked fine ([example](https://landscape.io/github/flother/htmltab/1)) until I added a `.landscape.yml` file to my repo, at which point Landscape checks always fail. I pushed after both flother/htmltab@7819144bd9fc21bbac1ef6a77f79f21d38e9e915 and flother/htmltab@cd5b32375a07f1a42c595e2b2dd23178477129f5; Landscape checks failed after both pushes.

If I run Prospector locally it picks up the `.landscape.yml` file and runs its checks successfully. I'm running version 0.12 of Prospector under Python 3.5.1.

**Comment by lewismc** [comment]
This issue has been resolved at #243 thanks @carlio

**Comment by flother** [comment]
The issue's not resolved for me, Landscape still fails in the way. I think my issue is a duplicate of #233: when you enable Vulture, Landscape fails, and it won't work again even if you disable Vulture.

**Comment by mbdevpl** [comment]
I'm having the same issue with my repo https://landscape.io/github/mbdevpl/typed-astunparse - such things were happening before, as in issue #180, but I think no fix was actually performed. And I don't have any spaces at the ends of lines of my `.landscape.yaml` (which was the issue in #243).

> Check number 6 has failed. This is almost always due to a bug in Landscape - we have been notified. Sorry about that.
> Failure reason: Prospector execution failed
> 
> The checking tool, prospector, did not complete correctly

Is there any way to see some logs of what is going on? The traceback? There is some extra space on that error page to add some output ;) I guess I feel the same as OP in #95:

> Maybe you should consider provide more logs about prospector fail, because i think it can be fixed in my project by config file.

and some other quote:

> I'm also left in the dark with a failure, with little indications or hints.

I'm really reluctant on debugging a tool that should be telling me what I'm doing wrong or right, in order to see what the tool is doing wrong or right ;)

I think both sides (app developer and landscape team) would benefit greatly from more verbosity on that error page.
