### ISSUE TITLE
Failure reason: Unknown

### ISSUE THREAD

**Issue by nicolaschotard** [landscapeio/landscape-issues#258]
Hello,

For some unknown reasons, all my Landscape runs fail with the following message, and I cannot figure out why:

> Oh
>
> No
>
>Check number 358 has failed. This is almost always due to a bug in Landscape - we have been >notified. Sorry about that.
>Failure reason: Unknown
>
>We don't know exactly why this error happened yet

Is there a way to check the output log of the run? This will definitely help in understanding why the runs fail, and see if the bug comes from the code, the configuration, or from landscape itself.

I've also run prospector 0.12.4 on my laptop for this project (for python 2.7) and haven't seen any error.

Here is the link to the landscape page:

https://landscape.io/github/nicolaschotard/Clusters

Thanks a lot for your help!

**Comment by woutervh** [comment]
i have the same problem since 3 weeks.
it should be more clear what is the problem.

I just started using landscape, and after a few commits after always fails
I should just wait for you to fix something?
3 weeks, 3months, 3 years?

i'm getting disappointed

**Comment by carlio** [comment]
Hi @nicolaschotard - These are actually fixed now, I forgot to update this issue. The problem was one of the checkers ran out of disk space and didn't correctly get removed from the pool. I've since added better monitoring for this kind of issue in the future.

Hi @WouterVH - I looked into it and it turns out to be a bug in prospector at detecting filencoding from this file on one of the lines near here: https://github.com/bots-edi/bots/blob/master/tests/unit_multi_1.py#L77 . You can see the failure if you run prospector yourself locally. Obviously this error message and encoding handling needs to be improved!

**Comment by tovmeod** [comment]
I just retried the check and still getting Failure reason: Unknown

https://landscape.io/github/tovmeod/anaf/68

**Comment by nicolaschotard** [comment]
@carlio I reactive this issue because I have the exact same problem for an other project ([here](https://landscape.io/github/nicolaschotard/bpz/)). All the check that run the past month ended up with this `Failure reason: Unknown`. Is it also a problem of disk space on the worker? 

And by the way, thanks for fixing the problem for the other repo!

**Comment by nolanbconaway** [comment]
Having this problem, what's up?

https://landscape.io/github/AusterweilLab/jarjar/14
