### ISSUE TITLE
Prospector execution failed

### ISSUE THREAD

**Issue by biergaizi** [landscapeio/landscape-issues#49]
Half a year ago, I tried Landscape to analyze my project (WeCase/WeCase), but it still broken today...

```
Check number 18 has failed. This is almost always due to a bug in Landscape - we have been notified. Sorry about that.

Failure reason: Prospector execution failed

Prospector did not complete correctly
```

**Comment by carlio** [comment]
This appears to work now! I fixed numerous bugs which could have caused this, so I'm not sure which problem occurred for you exactly. However, woo!

**Comment by biergaizi** [comment]
Good job! :+1:

**Comment by aldor007** [comment]
Hi
 I have the same error with project Teleinformatyka/RedSparrow. I was trying to add/delete .landscape.yaml but with no luck - it's still not working. Maybe you should consider provide more logs about prospector fail, because i think it can be fixed in my project by config file.
